# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  package:
      docker:
        - image: circleci/node:8.10
      working_directory: ~/repo
      steps:
        - checkout
        - run: npm i
        - run: npm i serverless@1.30.3
        - run:
            name: Serverless Package
            command: "SLS_DEBUG=* node_modules/.bin/serverless package -v"
        - run: 
            name: Deploy to dev
            command: .circleci/deploy.sh dev

  deploy_to_test:
      docker:
        - image: circleci/node:8.10
      working_directory: ~/repo
      steps:
        - run: 
            name: Deploy to dev
            command: .circleci/deploy.sh dev

  deploy:
      docker:
        - image: circleci/node:8.10
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        - run: npm i
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - run: npm test
        - run: npm i serverless@1.30.3
        - run: 
            name: Deploy to staging
            command: .circleci/deploy.sh staging
        - run:
            name: Deploy to prod
            command: .circleci/deploy.sh production

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - package:
         requires:
            - build
      - deploy_to_test:
         requires:
            - build
            - package
         context: "aws.amazon.com/alexjpaz/circleci"
         filters:
           branches:
             ignore: master
      - deploy:
         requires:
            - build
         context: "aws.amazon.com/alexjpaz/circleci"
         filters:
           branches:
            only: master
